float2 Offset = 0.0f;
float PixelSum = 0.0f;
float WeightSum = 0;

for (int x = -Radius; x <= Radius; x++)
{
	for (int y = -Radius; y <= Radius; y++)
	{
		Offset = UVs + float2(x, y) * (Size / Radius);
		float3 PixelColor = Texture2DSample(Tex, TexSampler, Offset);
		float Weight = Gaussian1D(x / Radius) * Gaussian1D(y / Radius);
		PixelSum += PixelColor * Weight;
		WeightSum += Weight;
	}
}
return PixelSum / WeightSum;